export const LOCATORS = {
  HOME: {
    LOGO: 'img[alt="Website for automation practice"]',
    NAV_BAR: 'header#header .navbar',
    SIGNUP_LOGIN_LINK: 'a[href="/login"]',
    LOGGED_IN_TEXT: 'li:has-text("Logged in as")',
    DELETE_ACCOUNT_LINK: 'a[href="/delete_account"]',
  },
  SIGNUP_LOGIN: {
    NEW_USER_HEADER: 'h2:has-text("New User Signup!")',
    SIGNUP_NAME_INPUT: 'input[data-qa="signup-name"]',
    SIGNUP_EMAIL_INPUT: 'input[data-qa="signup-email"]',
    SIGNUP_BUTTON: 'button[data-qa="signup-button"]',
    LOGIN_HEADER: 'h2:has-text("Login to your account")',
    LOGIN_EMAIL_INPUT: 'input[data-qa="login-email"]',
    LOGIN_PASSWORD_INPUT: 'input[data-qa="login-password"]',
    LOGIN_BUTTON: 'button[data-qa="login-button"]',
    LOGIN_ERROR_MESSAGE: 'p[style*="color: red"]',
  },
  SIGNUP: {
    ACCOUNT_INFO_HEADER: 'b:text-is("Enter Account Information")',
    TITLE_MR: 'input#id_gender1',
    TITLE_MRS: 'input#id_gender2',
    NAME_INPUT: 'input[data-qa="name"]',
    EMAIL_INPUT: 'input[data-qa="email"]',
    PASSWORD_INPUT: 'input[data-qa="password"]',
    DAY_DROPDOWN: 'select[data-qa="days"]',
    MONTH_DROPDOWN: 'select[data-qa="months"]',
    YEAR_DROPDOWN: 'select[data-qa="years"]',
    NEWSLETTER_CHECKBOX: 'input#newsletter',
    OFFERS_CHECKBOX: 'input#optin',
    FIRST_NAME_INPUT: 'input[data-qa="first_name"]',
    LAST_NAME_INPUT: 'input[data-qa="last_name"]',
    COMPANY_INPUT: 'input[data-qa="company"]',
    ADDRESS1_INPUT: 'input[data-qa="address"]',
    ADDRESS2_INPUT: 'input[data-qa="address2"]',
    COUNTRY_DROPDOWN: 'select[data-qa="country"]',
    STATE_INPUT: 'input[data-qa="state"]',
    CITY_INPUT: 'input[data-qa="city"]',
    ZIPCODE_INPUT: 'input[data-qa="zipcode"]',
    MOBILE_INPUT: 'input[data-qa="mobile_number"]',
    CREATE_ACCOUNT_BUTTON: 'button[data-qa="create-account"]',
  },
  ACCOUNT_CREATED: {
    HEADER: 'h2[data-qa="account-created"]',
    CONTINUE_BUTTON: 'a[data-qa="continue-button"]',
  },
  ACCOUNT_DELETED: {
    HEADER: 'h2[data-qa="account-deleted"]',
    CONTINUE_BUTTON: 'a[data-qa="continue-button"]',
  },
} as const;
